### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by darrenhaken** [lensesio/kafka-connect-ui#99]
I have noticed you've been trying to push your paid-for product and haven't made any changes to this repository in nearly a year.

Is it fair to say you've abandoned open source and are now focusing solely on your paid product?
I'd really like to know if this repository will be maintained or not.

**Comment by carlosjgp** [comment]
@darrenhaken 
It appears it's not...
https://twitter.com/CarlosJuanGP/status/1266083344145678339?s=19

I'll be catching up with them soon.

I'll keep you posted

**Comment by darrenhaken** [comment]
Do keep me posted, the projects have been very quiet. Thanks for pinging me

**Comment by EfstathiadisD** [comment]
Hello. No, this project is not abandoned. It is true, we are not as active as possible, and some PRS got stale, but we recently merged quite a few of them.

That being said, we do not maintain it full time, and thus will have a bit of a delay in our responses and PR Reviews.

**Comment by EfstathiadisD** [comment]
Please let me know if you have any questions. I will close the issue for the time being but please feel free to open it if you feel we are lacking behind too much. Thank you and happy new year 🎉 !!
